#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Ecgine
webVersion : Beta
signup: https://vimukti.ecgine.com/com.vimukti.ecgine.master/signup

# Short bio or description (displayed in the header)
description: The unified business software suite

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/website-logo.png

# URL of ecgine screen shot pic
downloadimage: /images/ecginescreenshot.jpg
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: info@ecgine.com
  facebook: Ecgine
  flickr:
  github: ecgine
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: ecgine
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-36897668-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
collections:
  faqs:
#########################
# Plugin: jekyll-assets #
#########################

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/javascripts
    - _assets/images
    - _assets/stylesheets
    - _assets/fonts

  # Minify and Compress Assets
  compress:
    css: sass
    js: uglifier

  # Disable asset gzip
  gzip: false